image: $CI_REGISTRY_IMAGE

# Disable the Gradle daemon
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Make the gradle wrapper executable.
before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew clean assemble
  allow_failure: false

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew check
