image: $CI_REGISTRY_IMAGE

# Disable the Gradle daemon
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - chmod +x gradlew # Make the gradle wrapper executable.
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 # Ensure UF8 encoding.

build:
  stage: build
  script:
    - ./gradlew clean assemble
  allow_failure: false

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew check
