image: $CI_REGISTRY_IMAGE

# Disable the Gradle daemon
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - build/
    - core/build/
    - cli/build/

# Make the gradle wrapper executable.
before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew clean assemble
  allow_failure: false

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew test integrationTest
  artifacts:
    reports:
      junit:
        - core/build/test-results/test/TEST-*.xml
        - core/build/test-results/integrationTest/TEST-*.xml

# Publish generated test reports as artifact
test-reports:
  stage: test
  dependencies:
    - test
  script:
    - mkdir reports
    - mv core/build/reports/tests/ reports
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    expire_in: 4 days
    paths:
      - reports/
  when: always
